apiVersion: v1
kind: Secret
metadata:
  name: {{ include "junior.fullname" . }}-secrets
  labels:
    {{- include "junior.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  github-token: {{ .Values.secrets.githubToken | b64enc | quote }}
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}